#!/usr/bin/zsh

# Do not call this script directly.
# Include this into your .zshrc like
# source ~/git/jerolimov/openshift/scripts/zshconfig

# k8s & co. auto completion
command -v kubectl &>/dev/null &&   source <(kubectl completion zsh)
command -v oc &>/dev/null &&        source <(oc completion zsh)
command -v kn &>/dev/null &&        source <(kn completion zsh)
command -v tkn &>/dev/null &&       source <(tkn completion zsh)
command -v helm &>/dev/null &&      source <(helm completion zsh)
command -v kompose &>/dev/null &&   source <(kompose completion zsh)
command -v minikube &>/dev/null &&  source <(minikube completion zsh)

for script in ~/git/jerolimov/openshift/scripts/*.sh;
do
    cmd=$(basename "$script" | sed 's/.sh$//')
    alias "$cmd=$script"
done
