#!/usr/bin/zsh

# Do not call this script directly.
# Include this into your .zshrc like
# source ~/git/jerolimov/openshift/scripts/zshconfig

# k8s & co. auto completion
source <(kubectl completion zsh)
source <(oc completion zsh)
source <(kn completion zsh)
source <(tkn completion zsh)
source <(helm completion zsh)
source <(kompose completion zsh)
source <(minikube completion zsh)

for script in ~/git/jerolimov/openshift/scripts/*.sh;
do
    cmd=$(basename "$script" | sed 's/.sh//')
    alias "$cmd=$script"
done
